# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
variables:
  storageContainer: storageppfedev001
  azureSubscription: '5bf6c4f0-d61d-44db-aa07-b364f8527f71'
  vmImageName: ubuntu-latest
  environmentName: dev
  buildArtifacts: www

trigger:
- releases/development
- master

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    - script: |
        npm install -g @angular/cli
        npm install
        ng build
      displayName: 'npm install and build'
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Web Build'
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/$(buildArtifacts)'

      